// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdphGjGaO4bwRgY47dx7gYX5PgOJ1atrk',
    appId: '1:1089309118337:web:7d8991b9a69301b9742280',
    messagingSenderId: '1089309118337',
    projectId: 'jen1-text-app',
    authDomain: 'jen1-text-app.firebaseapp.com',
    storageBucket: 'jen1-text-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnq4c_Yzoc15q2Jlrn4mNBtjosg0WTE6I',
    appId: '1:1089309118337:android:45e4107ceb075100742280',
    messagingSenderId: '1089309118337',
    projectId: 'jen1-text-app',
    storageBucket: 'jen1-text-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBQ9PvVRO6Bhq-WIxbZT1rihkDF63tZDI',
    appId: '1:1089309118337:ios:a78c544bd9a23960742280',
    messagingSenderId: '1089309118337',
    projectId: 'jen1-text-app',
    storageBucket: 'jen1-text-app.firebasestorage.app',
    androidClientId: '1089309118337-c104f41q4falcvvrbm893tgvl94ph0id.apps.googleusercontent.com',
    iosClientId: '1089309118337-0glv6mfmhgl779jq0mf42dl1orin8425.apps.googleusercontent.com',
    iosBundleId: 'com.example.textApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBQ9PvVRO6Bhq-WIxbZT1rihkDF63tZDI',
    appId: '1:1089309118337:ios:a78c544bd9a23960742280',
    messagingSenderId: '1089309118337',
    projectId: 'jen1-text-app',
    storageBucket: 'jen1-text-app.firebasestorage.app',
    androidClientId: '1089309118337-c104f41q4falcvvrbm893tgvl94ph0id.apps.googleusercontent.com',
    iosClientId: '1089309118337-0glv6mfmhgl779jq0mf42dl1orin8425.apps.googleusercontent.com',
    iosBundleId: 'com.example.textApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdphGjGaO4bwRgY47dx7gYX5PgOJ1atrk',
    appId: '1:1089309118337:web:8eb703494eb8a566742280',
    messagingSenderId: '1089309118337',
    projectId: 'jen1-text-app',
    authDomain: 'jen1-text-app.firebaseapp.com',
    storageBucket: 'jen1-text-app.firebasestorage.app',
  );
}
